backend:
  # name: git-gateway
  name: test-repo
  branch: master

media_folder: static/uploads # Media files will be stored here
public_folder: /uploads # Part of the path where to access the media in the built project

collections:
  - name: authors # Used in routes, e.g. /admin/collections/authors
    label: Authors # label in the admin UI
    folder: src/content/authors # Path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      # - label: ""
      - label: "Books"
        name: "books"
        widget: "list"
        fields:
           - label: "Book"
             name: "book"
             widget: "object"
             fields:
              - {label: "Title", name: "title", widget: "text"}

  - name: "books"
    label: "Books"
    folder: "src/content/books"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
