backend:
  # name: git-gateway
  name: test-repo
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "authors"
    label: "Authors"
    folder: "src/content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}

  - name: "books"
    label: "Books"
    folder: "src/content/books"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
